name: Continuous Integration
on:
  push:
    branches: [ "feature**" ]
  workflow_dispatch:
  
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - name: Install Packages
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make train
      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
  create-pull-request:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          branch: main

